########################################
#####  CODE                        #####
########################################

#####  CLASS
class API_KEY_ERROR(Exception): ...
class WorkSpaceNotFound(Exception): ...
class DirectoryNotFound(Exception): ...
class WorkSpaceAlreadyExists(Exception): ...
class CommandNotFound(Exception): ...
class PasswordError(Exception): ...
class NotCompatibleOS(Exception): ...
class MissingArgs(Exception): ...

#####  RUN FILE
if __name__ == "__main__":
    pass