name: Automate Issues

on:
  issues:
    types: [opened]

jobs:
  
  automated-issue:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v4

      # SetUp python
      - name: SetUp Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      # Install requirements
      - name: Install Requirements
        run: pip install requests

      # Runs a single command using the runners shell
      - name: Automate Issue
        env:
          API_KEY: ${{ secrets.API_KEY }}
          REPO: ${{ github.repository }}
        run: python .github/workflows/issues.py